import { StyleSheet } from 'react-native';

/**
 * Design tokens + shared styles, mirroring the web app so the two feel like
 * one product.
 */
export const theme = {
  bg: '#fbfbfd',
  surface: '#ffffff',
  surface2: '#f6f7f9',
  border: '#e6e8ec',
  text: '#0f172a',
  muted: '#64748b',
  muted2: '#94a3b8',
  accent: '#6366f1',
  accentWeak: '#eef2ff',
  accentStrong: '#4f46e5',
  ok: '#059669',
  okWeak: '#ecfdf5',
  warn: '#b45309',
  warnWeak: '#fffbeb',
  danger: '#dc2626',
  dangerWeak: '#fef2f2',
  radius: 12,
  radiusSm: 8,
} as const;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  content: { padding: 16, paddingBottom: 40 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  heading: { fontSize: 24, fontWeight: '600', color: theme.text, marginBottom: 4 },
  subheading: { fontSize: 14, color: theme.muted, marginBottom: 16 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.muted2,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 20,
    marginBottom: 8,
  },
  card: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: theme.radius,
    padding: 14,
    marginBottom: 10,
  },
  cardTight: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: theme.radiusSm,
    padding: 10,
    marginBottom: 8,
  },
  row: { flexDirection: 'row', alignItems: 'center' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { fontSize: 15, fontWeight: '600', color: theme.text },
  meta: { fontSize: 12, color: theme.muted },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '600',
    overflow: 'hidden',
  },
  badgeOk: { backgroundColor: theme.okWeak, color: theme.ok },
  badgeWarn: { backgroundColor: theme.warnWeak, color: theme.warn },
  badgeDanger: { backgroundColor: theme.dangerWeak, color: theme.danger },
  badgeInfo: { backgroundColor: theme.accentWeak, color: theme.accentStrong },
  badgeNeutral: { backgroundColor: theme.surface2, color: theme.muted },
  button: {
    backgroundColor: theme.accent,
    borderRadius: theme.radiusSm,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  buttonText: { color: '#fff', fontWeight: '600', fontSize: 15 },
  buttonGhost: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: theme.radiusSm,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  buttonGhostText: { color: theme.text, fontWeight: '600', fontSize: 15 },
  buttonSmall: {
    backgroundColor: theme.accentWeak,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: theme.radiusSm,
  },
  buttonSmallText: { color: theme.accentStrong, fontWeight: '600', fontSize: 13 },
  empty: { padding: 32, alignItems: 'center', color: theme.muted2, fontSize: 14 },
  error: {
    backgroundColor: theme.dangerWeak,
    color: theme.danger,
    padding: 12,
    borderRadius: theme.radiusSm,
    marginBottom: 12,
    fontSize: 14,
  },
  success: {
    backgroundColor: theme.okWeak,
    color: theme.ok,
    padding: 12,
    borderRadius: theme.radiusSm,
    marginBottom: 12,
    fontSize: 14,
  },
  bar: {
    height: 6,
    backgroundColor: theme.surface2,
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 6,
  },
  barFill: { height: '100%', backgroundColor: theme.accent, borderRadius: 999 },
  input: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    backgroundColor: theme.surface,
    color: theme.text,
  },
  label: { fontSize: 13, fontWeight: '500', color: theme.text, marginBottom: 6 },
  dayChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.border,
    marginRight: 8,
    backgroundColor: theme.surface,
  },
  dayChipActive: { backgroundColor: theme.accent, borderColor: theme.accent },
  dayChipText: { fontSize: 13, color: theme.muted, fontWeight: '500' },
  dayChipTextActive: { color: '#fff', fontWeight: '600' },
});
